# 服务器配置
server:
  port: 80
  context-path: /shadow
  session:
    timeout: 30
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000

# 主数据源配置
spring:
  datasource:
    url: jdbc:mysql://192.168.1.2:3306/lemon_2?characterEncoding=utf8&useSSL=true
    username: shadow
    password: 123456

