# 服务器配置
server:
  port: 8080
  context-path: /shadow
  session:
    timeout: 30
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000

# 主数据源配置
spring:
  datasource:
    url: jdbc:mysql://192.168.1.9:3306/shadow?characterEncoding=utf8&useSSL=true
    username: shadow
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    # 设置八小时连接超时
    test-while-idle: true
    validation-query: SELECT 1 FROM DUAL
    time-between-eviction-runs-millis: 300000
    # 连接池设置
    initial-size: 5
    min-idle: 5
    max-wait-millis: 60000
    max-total: 30
    min-evictable-idle-time-millis: 1800000
    test-on-borrow: true
    test-on-return: false
    pool-prepared-statements: true
    max-open-prepared-statements: 20
    default-read-only: false
  # 副数据源
  second-datasource:
    url: jdbc:mysql://192.168.1.9:3306/shadow?characterEncoding=utf8&useSSL=true
    username: shadow
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver


  # jpa 配置
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
